export enum EBillType {
  BOL = 'BOL',
  BOL_WITH_DRAFT = 'BOL_WITH_DRAFT',
  BOL_WITH_PATTERN = 'BOL_WITH_PATTERN',
  DRAFTS = 'DRAFTS',
  INVALID = 'INVALID',
  MISC = 'MISC',
  MISC_WITH_DRAFT = 'MISC_WITH_DRAFT',
  MISC_WITH_PATTERN = 'MISC_WITH_PATTERN',
  PATTERNS = 'PATTERNS',
  SUBMITTED_SHIPMENT_REQUESTS = 'SUBMITTED_SHIPMENT_REQUESTS',
  UPDATED_SUBMITTED_SHIPMENT_REQUESTS = 'UPDATED_SUBMITTED_SHIPMENT_REQUESTS',
  WAYBILL = 'WAYBILL',
  WAYBILL_WITH_DRAFT = 'WAYBILL_WITH_DRAFT',
  WAYBILL_WITH_PATTERN = 'WAYBILL_WITH_PATTERN'
}

export enum EBillSection {
  COMMODITY = 'commodity',
  COMMODITY_LADING = 'commodityLading',
  CUSTOMS = 'customs',
  EMPTY_REVERSE = 'emptyReverse',
  GENERAL = 'generalSetup',
  HAZARDOUS = 'hazardous',
  LOCATION = 'location',
  ORDER_SETUP = 'orderSetup',
  OTMA_LOAD_UP = 'otmaLoadUp',
  PROTECTIVE_SERVICE = 'protectiveService',
  RATING = 'rating',
  ROUTE = 'route',
  SHIPMENT_PARTIES = 'shipmentParties',
  SHIPMENT_REFERENCES = 'shipmentReferences',
  VIN = 'vin'
}

export enum EBillSectionLabel {
  COMMODITY = 'COMMODITY',
  COMMODITY_LADING = 'COMMODITY/LADING',
  CUSTOMS = 'CUSTOMS',
  EMPTY_REVERSE = 'EMPTY REVERSE',
  GENERAL = 'GENERAL',
  HAZARDOUS = 'HAZARDOUS',
  LOCATION = 'LOCATION',
  ORDER_SETUP = 'ORDER SETUP',
  OTMA_LOAD_UP = 'OTMA/LOAD-UP',
  PROTECTIVE_SERVICE = 'PROTECTIVE SERVICE',
  RATING = 'RATING',
  ROUTE = 'ROUTE',
  SHIPMENT_PARTIES = 'SHIPMENT PARTIES',
  SHIPMENT_REFERENCES = 'SHIPMENT REFERENCES',
  VIN = 'VIN'
}
