export enum EOrderOption {
  EMPTY_NON_REVENUE = 'EMPTY_NON_REVENUE',
  EMPTY_REVENUE = 'EMPTY_REVENUE',
  LOADED_MERCHANDISE = 'LOADED_MERCHANDISE',
  MISCELLANEOUS_BILL = 'MISCELLANEOUS_BILL',
  PROPER_TO_ACCRUE_MERCHANDISE = 'PROPER_TO_ACCRUE_MERCHANDISE',
  PROPER_TO_ACCRUE_RAIL_HIGHWAY = 'PROPER_TO_ACCRUE_RAIL_HIGHWAY',
  RAIL_HIGHWAY = 'RAIL_HIGHWAY',
  RAIL_MANIFEST = 'RAIL_MANIFEST',
  RESHIP = 'RESHIP',
  UNIT_TRAIN = 'UNIT_TRAIN'
}
